matrix:
  include:
    - os: linux
      dist: trusty
      language: python
      python: "3.6"
    - os: linux
      dist: trusty
      language: python
      python: "2.7"

cache:
  pip: true

install:
  - pip install -r requirements-dev.txt

script:
  - make codespell
  - make flake8
  - make pytest

deploy:
  provider: pypi
  user: $PYPIUSER
  password: $PYPIPASSWORD
  distributions: "sdist"
  on:
    branch: master
    python: "3.6"
    tags: true
